version: 2
jobs:
  build:
    
    working_directory: ~/circleci-sewer

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: circleci-sewer-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-sewer-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: core/target/surefire-reports
      
      - store_artifacts:
          path: core/target/core-0.1.0-SNAPSHOT.jar

